import "@/styles/globals.css";
import Head from "next/head";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>ShoeStopper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/jpeg" href="/Air-Jordan.jpeg" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}
